// <auto-generated />
using System;
using Janken.Runtime.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Janken.Runtime.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Janken.Runtime.Models.Choice", b =>
                {
                    b.Property<Guid>("ChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("ChoiceId");

                    b.ToTable("Choice");

                    b.HasData(
                        new
                        {
                            ChoiceId = new Guid("2f46b2a9-9119-46a6-8907-38fcca07ab99"),
                            Name = "type",
                            Value = 0
                        },
                        new
                        {
                            ChoiceId = new Guid("1a185093-9699-427c-a507-9d3b97af1d07"),
                            Name = "type",
                            Value = 1
                        },
                        new
                        {
                            ChoiceId = new Guid("95382d2c-feea-41fa-80f1-7b79b6c41293"),
                            Name = "type",
                            Value = 2
                        },
                        new
                        {
                            ChoiceId = new Guid("450996c0-1a06-47e2-b97c-ce99e6774dce"),
                            Name = "type",
                            Value = 3
                        });
                });

            modelBuilder.Entity("Janken.Runtime.Models.Player", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Computer")
                        .HasColumnType("bit");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            PlayerId = new Guid("a05e7a2e-3e97-4b54-bec5-c2aa57512a8b"),
                            Computer = true,
                            Handle = "",
                            Password = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
